stages:
  - build

variables:
  DEVELOP_URL: "${CI_REGISTRY_IMAGE}/development"

before_script:
  - curl https://code.ornl.gov/rse-deployment/rse-sharables/raw/master/rse-bash-modules.sh -O
  - source rse-bash-modules.sh
  - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
  - func_rse_docker_cleanup

after_script:
  - curl https://code.ornl.gov/rse-deployment/rse-sharables/raw/master/rse-bash-modules.sh -O
  - source rse-bash-modules.sh
  - func_rse_docker_cleanup
  - sudo chown -R gitlab-runner .

build:
  stage: build
  script:
    - >
      docker build
      -t $DEVELOP_URL/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA .
    - docker tag $DEVELOP_URL/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA $DEVELOP_URL/$CI_COMMIT_REF_NAME:latest
    - docker push $DEVELOP_URL/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
    - docker push $DEVELOP_URL/$CI_COMMIT_REF_NAME:latest
  tags:
    - intersect-sdk-builder
