[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "neeter_active_learning"
version = "0.1.0"
authors = [
    {name = "David Joy", email = "joydh1@ornl.gov"},
]
description = "NEETER active learning using INTERSECT SDK"
readme = "README.md"
requires-python = ">=3.9"
keywords = ["active learning"]
#license = {text = "BSD-3-Clause"}
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "intersect_sdk>=0.5.0,<0.6.0",
]