name: CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Ruff linting, formating, MyPy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup UV
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          uv sync --locked --all-extras --all-groups
      - name: Run linters and type checks
        run: |
          uv run ruff format --check
          uv run ruff check

  test-all:
    name: Unit tests on various OSes and Python versions
    strategy:
      matrix:
        python-version:
          - python-version: "3.10"
            continue-on-error: true
          - python-version: "3.11"
            continue-on-error: true
          - python-version: "3.12"
            continue-on-error: true
          # TODO - fix issue with Jaxlib not installing
          - python-version: "3.13"
            continue-on-error: true
          - python-version: "3.14"
            continue-on-error: true
        os:
          - os: macos-latest
            continue-on-error: true
          - os: windows-latest
            continue-on-error: true
          - os: ubuntu-latest
            continue-on-error: true
    runs-on: ${{ matrix.os.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Setup UV
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          uv sync --locked --all-extras --all-groups
        continue-on-error: ${{ matrix.os.continue-on-error || matrix.python-version.continue-on-error }}
      - run: pytest tests/ --cov=src/ --cov-report=html:reports/htmlcov/ --cov-report=xml:reports/coverage_report.xml --junitxml=reports/junit.xml
        continue-on-error: ${{ matrix.os.continue-on-error || matrix.python-version.continue-on-error }}

  docker-test:
    name: Build Docker image and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t dial:test --target builder --build-arg UV_NO_DEV=0 .
      - name: Run tests in container
        run: docker run --rm -v $PWD/tests:/app/tests/ dial:test uv run pytest tests/
        continue-on-error: true

  continuous-deployment:
    name: Update deployments automatically
    needs: ['lint', 'test-all', 'docker-test']
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Kickoff pipeline
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          curl --fail-with-body \
          --form token=${GITLAB_TOKEN} \
          --form ref=main \
          --form "variables[TRIGGER_BRANCH]=${{ github.ref_name }}" \
          "https://code.ornl.gov/api/v4/projects/17316/trigger/pipeline"
